### ISSUE TITLE
windows 运行问题

### ISSUE THREAD

**Issue by hwk603** [wwj718/ibot#1]
针对下面这段代码：

```
home = expanduser("~")
with open(os.path.join(home,".ibot.yml")) as f:
    config = yaml.load(f)
    bosonnlp_token = config["token"]
```

如何在 windows 系统上进行修改，我自己在 `c:\user\` 创建了一个 `.ibot.yml` 的文件，然后把 BosonNLP 的 token 复制进去，出现如下的错误：

```
> ibot
Traceback (most recent call last):
  File "D:\software\python35\Scripts\ibot-script.py", line 9, in <module>
    load_entry_point('ibot==0.1.1', 'console_scripts', 'ibot')()
  File "D:\software\python35\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\software\python35\lib\site-packages\pkg_resources\__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "D:\software\python35\lib\site-packages\pkg_resources\__init__.py", line 2229, in load
    return self.resolve()
  File "D:\software\python35\lib\site-packages\pkg_resources\__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\software\python35\lib\site-packages\ibot\ibot.py", line 16, in <module>
    bosonnlp_token = config["token"]
TypeError: string indices must be integers 
```

感觉应该是 `.ibot.yml` 这个文件格式的问题？

**Comment by wwj718** [comment]
这是个文件路径的问题，linux和mac都有home目录，微软下我不大清楚呢，你可以手写这个目录和文件

**Comment by hwk603** [comment]
好的，我已经知道问题出在哪了。我之后修改了一下 `/ibot.yml` 的格式：

```
token: API密钥
```

之前应该是 `YAML` 语法写错了。。

**Comment by wwj718** [comment]
👍
