### ISSUE TITLE
how to set bosonnlp's .ibot.yml

### ISSUE THREAD

**Issue by SeekPoint** [wwj718/ibot#2]
would you like to  share a qucik demo?
```

**Comment by wwj718** [comment]
if you use mac/linux , just create a file(`~/.ibot.yml`) , like this:

```
token: xxxxx
```

 click  [here](http://bosonnlp.com/) to get the token

**Comment by SeekPoint** [comment]
thanks a quick reply。
I need a quick evaluation on this project,so

rzai@rzai00:~/prj/ibot$ python3
Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > ibot 明天从南京到北京的车票
> > >   File "<stdin>", line 1
> > >     ibot 明天从南京到北京的车票
> > >                    ^
> > > how can i make it works?

**Comment by wwj718** [comment]
@loveJasmine  just use pip3 to install ibot

![image](https://cloud.githubusercontent.com/assets/3153878/20375309/72f7a902-acb9-11e6-930b-a47cdd347c8f.png)

**Comment by SeekPoint** [comment]
rzai@rzai00:~/prj$ sudo pip3 install ibot
[sudo] password for rzai: 
Requirement already satisfied (use --upgrade to upgrade): ibot in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): iquery in /usr/local/lib/python3.4/dist-packages (from ibot)
Requirement already satisfied (use --upgrade to upgrade): bosonnlp in /usr/local/lib/python3.4/dist-packages (from ibot)
Cleaning up...
rzai@rzai00:~/prj$ 
rzai@rzai00:~/prj$ cat ~/.ibot.yml
cat: /home/rzai/.ibot.yml: No such file or directory
rzai@rzai00:~/prj$ ibot 明天从南京到北京的车票
Traceback (most recent call last):
  File "/usr/local/bin/ibot", line 11, in <module>
    load_entry_point('ibot==0.1.1', 'console_scripts', 'ibot')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/**init**.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/**init**.py", line 2612, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/**init**.py", line 2272, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/**init**.py", line 2278, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/ibot/ibot.py", line 14, in <module>
    with open(os.path.join(home,".ibot.yml")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rzai/.ibot.yml'
rzai@rzai00:~/prj$ 

so, the root cause is I don't konw how to write my own ibot.yml

**Comment by wwj718** [comment]
create the file(`~/.ibot.yml`) by yourself

**Comment by SeekPoint** [comment]
what's the content of ibot.yml?

**Comment by wwj718** [comment]
![image](https://cloud.githubusercontent.com/assets/3153878/20390436/d5107876-ad09-11e6-8bb9-f1981ac3e7ce.png)
